uploader rewrite

diff --git a/sharingUtils b/sharingUtils
--- a/sharingUtils
+++ b/sharingUtils
@@ -5,56 +5,62 @@
 
 up() {
 
-  if [[ -z "$1" ]]; then echo Invalid Input; return; fi
-  if [[ -e "$1.zip" ]]; then
-    file="$1.zip"
-  elif [[ -e "$1.7z" ]]; then
-    file="$1.7z"
-  elif [[ -d "$1" ]]; then
-    zip -qr - "$1" | pv -bep -s $(du -bs "$1" | awk '{print $1}') > "$1.zip"
-    file="$1.zip"
-    zipped=true
-  elif [[ -e "$1" ]]; then
-    file="$1"
-  fi
-  serv=$(curl -s 'https://api.gofile.io/getServer' | jq -r .data.server)
-  if [[ -n "$noshorten" ]]; then
-    unset noshorten
-    curl -# -F token="$GOFILE_API_KEY" -F folderId="$GOFILE_FOLDER_ID" -F "file=@$file" "https://$serv.gofile.io/uploadFile" | jq -r .data.directLink
+  unset file link
+  trap 'unset file link; return' 2 3
+  if [[ "$1" =~ [a|g|G] ]]; then
+    choice="$1"
+  elif [[ "$2" =~ [a|g|G] ]]; then
+    choice="$2"
   else
-    sgo $(curl -# -F token="$GOFILE_API_KEY" -F folderId="$GOFILE_FOLDER_ID" -F "file=@$file" "https://$serv.gofile.io/uploadFile" | jq -r .data.directLink)
+    echo
+    echo -e '\e[35m# uploader\e[0m'
+    echo
+    echo -e '\e[32m[g] - gofile public'
+    echo '[G] - gofile private'
+    echo '[a] - anonfiles'
+    echo
+    echo -e '\e[33m[s] - shorten result'
+    echo -e '\e[31m[e] - exit\e[0m'
+    echo
+    read -p 'option : ' choice
   fi
-  if [[ -n "$zipped" ]]; then
-    unset zipped
-    rm "$1".zip
+  if [[ -f "$1" ]]; then
+    file="$1"
+  elif [[ -f "$2" ]]; then
+    file="$2"
+  else
+    read -p 'file : ' file
+    if [[ ! -s "$file" ]]; then
+      echo -e '\e[31mInvalid file\e[0m\n'
+      return
+    fi
   fi
+  echo
+  for ((i=0; i < "${#choice}"; i++)); do
+    case "${choice:i:1}" in
+      g) serv=$(curl -s 'https://api.gofile.io/getServer' | jq -r .data.server)
+         link=$(curl -# -F token="$GOFILE_API_KEY" -F folderId="$GOFILE_PUBLIC_FOLDER_ID" -F "file=@$file" "https://$serv.gofile.io/uploadFile" | jq -r .data.downloadPage);;
+      G) serv=$(curl -s 'https://api.gofile.io/getServer' | jq -r .data.server)
+         link=$(curl -# -F token="$GOFILE_API_KEY" -F folderId="$GOFILE_PRIVATE_FOLDER_ID" -F "file=@$file" "https://$serv.gofile.io/uploadFile" | jq -r .data.downloadPage);;
+      a) link=$(curl -# -F "file=@$file" "https://api.anonfiles.com/upload?token=$ANONFILES_API_KEY" | jq -r .data.file.url.full);;
+      s) if [[ -n "$link" ]]; then
+           sgo "$link"
+           unset link
+         else
+           echo -e "\e[31mFail\e[0m\n"
+           return
+         fi;;
+      e) echo; return;;
+    esac
+    if [[ ! "${choice:i+1:1}" == 's' && -n "$link" ]]; then
+      echo -e "\n\e[32m$link\e[0m\n"
+    fi
+  done
+  unset file link
 
 }
 
-upl() {
-  noshorten=true
-  up "$@"
-}
-
-anon() {
-
-  link=$(curl -# -F "file=@$1" "https://api.anonfiles.com/upload?token=$ANONFILES_API_KEY" \
-  | jq -r .data.file.url.full)
-  if [[ -z "$link" ]]; then
-    echo "Failed"
-    return
-  fi
-  printf "$1 > $link\n" >> ~/.temp/last/urls
-  echo "$link"
-
-}
-
-anonfiles() {
-  url "https://anonfiles.com/?p=1"
-}
-
-
-# url shortener
+# url shorteners
 
 1o2() {
 
